config/routes.rb
FoodService::Application.routes.draw do
  resources :requests

  get 'calendar/:year/:month' => 'home#calendar', :as => 'show_month'

  root :to => "home#calendar"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :requests, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	before_filter :authenticate_user!

  def index
    @users = User.all 
    
  end

  def calendar
  	now = Time.now
    year = now.year
    month = now.month


    
    if params[:year]
      year = Integer(params[:year])
    end
    if params[:month]
      month = Integer(params[:month])
    end
    @user = current_user
    set_month_info(month, year)
    
    
    render 'calendar'
  end

  private

  def set_month_info(month, year)
    month_start = Time.zone.local year, month, 1
    month_end = Time.zone.local year, month, Time.days_in_month(month)
    date_range = month_start.to_date..month_end.to_date
    selected_month = Date.new(year, month)
    this_month_requests = Hash[(@user.requests.where(:date => selected_month..selected_month >> 1)).map { |r| [r.date, r]}]

    date_infos = date_range.map{|d| {
        date: d,
        request: this_month_requests[d]
    }}


    prev_month = month -1
    prev_year = year
    if prev_month == 0
      prev_month = 12
      prev_year = year -1
    end

    next_month = month + 1
    next_year = year
    if next_month == 13
      next_month = 1
      next_year = year + 1
    end

    @month_info = {
        :month => month,
        :year => year,
        :prev_month => prev_month,
        :prev_year => prev_year,
        :next_month => next_month,
        :next_year => next_year,
        :dates => date_infos,
        :today => Time.zone.now.midnight
    }
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
    puts current_user()
    @request.user_id = current_user().id    
    @request.date = params[:date].to_date
    

    respond_to do |format|
      if canCreate(@request) && @request.save
          format.json { render json: @request, status: :created, location: @request }
        else
          format.html { render action: "new" }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
    end
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
     @request = Request.find(params[:id])

    respond_to do |format|
      if canDestroy @request && @request.destroy!
        format.json { render :nothing => true,  status: :no_content }
      else
        format.json { render :nothing => true,  status: :forbidden }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:user_id, :date)
    end

    def canCreate(request)
    #todo: allow to create requests only in the future
    if Request.find_by date:request[:date]
      return false
    end
    return true
  end
   def canDestroy(request)
    #todo: allow to destroy only request without orders
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/_date.html.erb
<%
   date = date_info[:date]
   content_classes = ' date '
   data_attributes = " date=#{date.to_s} "
   if date.saturday? || date.sunday?
     content_classes += ' weekend '
   end
   if date < @month_info[:today]
     content_classes += ' past '
   else
     content_classes += ' future '
   end
   request = date_info[:request]
   if !request.nil?
     content_classes += ' ordered '
     data_attributes += " request_id=#{date_info[:request][:id]} "
   end
%>
<div class="date-container">
  <div class="<%=content_classes%>" <%=data_attributes%>>
      <b class="mday"><%= date.mday %></b>
  </div>
  
</div>

app/views/home/calendar.html.erb
<%
   prev_path = show_month_path({:year => @month_info[:prev_year], :month => @month_info[:prev_month]})
   next_path = show_month_path({:year => @month_info[:next_year], :month => @month_info[:next_month]})

   def render_invisible_dates
     html = ''
     month_start = @month_info[:dates].first[:date]
     i = 0
     while i < month_start.wday
       html += '<div class="date-container invisible-date-container"></div>'
       i += 1;
     end
     return html
   end
%>
<div class="nav">
  <a class="nav-button" href="<%=prev_path%>">&#60;</a>
  <label><%=@month_info[:dates].first[:date].strftime("%B") + ' ' +  @month_info[:year].to_s%></label>
  <a class="nav-button" href="<%=next_path%>">&#62;</a>
</div>
<div class="month-container">
  <%
     html = render_invisible_dates
     @month_info[:dates].each do |di|
       html += render partial: 'date', locals: {date_info: di}
     end
  %>
  <%= html.html_safe %>

</div>

<script>
    $(document).ready(function() {
        month_page = new MonthPage({
            create_url: '<%=new_request_path%>',
            delete_url: '<%=requests_path%>'
        });
    });
</script>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/home/month.html.erb
<%
   def render_invisible_dates
     html = ''
     month_start = @month_info[:dates].first[:date]
     i = 0
     while i < month_start.wday
       html += '<div class="date-container invisible-date-container"></div>'
       i += 1;
     end
     return html
   end
%>

<div class="month-container">
  <%
     html = render_invisible_dates
     @month_info[:dates].each do |di|
       html += render partial: 'date', locals: {date_info: di}
     end
  %>
  <%= html.html_safe %>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Foodservice", root_path, :class => 'brand' %>
<ul class="nav">
  
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Calendar',  root_path %>
    </li>
    <li>
    <%= link_to 'Requests', requests_path %>
    </li>
</ul>

<ul class="nav pull-right">
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>

  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Foodservice" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Foodservice" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/requests/_form.html.erb
<%= simple_form_for(@request) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.user %></td>
        <td><%= request.date %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.user %>
</p>

<p>
  <strong>Date:</strong>
  <%= @request.date %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/calendar.html.erb
<%
   prev_path = show_home_path({:year => @month_info[:prev_year], :month => @month_info[:prev_month]})
   next_path = show_home_path({:year => @month_info[:next_year], :month => @month_info[:next_month]})

   def render_invisible_dates
     html = ''
     month_start = @month_info[:dates].first[:date]
     i = 0
     while i < month_start.wday
       html += '<div class="date-container invisible-date-container"></div>'
       i += 1;
     end
     return html
   end
%>
<div class="nav">
  <a class="nav-button" href="<%=prev_path%>">&#60;</a>
  <label><%=@month_info[:dates].first[:date].strftime("%B") + ' ' +  @month_info[:year].to_s%></label>
  <a class="nav-button" href="<%=next_path%>">&#62;</a>
</div>
<div class="month-container">
  <%
     html = render_invisible_dates
     @month_info[:dates].each do |di|
       html += render partial: 'date', locals: {date_info: di}
     end
  %>
  <%= html.html_safe %>

</div>

<script>
    $(document).ready(function() {
        month_page = new MonthPage({
            create_url: '<%=new_request_path%>',
            delete_url: '<%=requests_path%>'
        });
    });
</script>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>